---
apiVersion: v1
kind: Service
metadata:
  name: opensource-rspack-lib
  namespace: frontend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: opensource-rspack-lib
