---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensource-rspack-lib
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensource-rspack-lib
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: opensource-rspack-lib
    spec:
      containers:
        - name: opensource-rspack-lib
          image: registry.digitalocean.com/fillet-dev/opensource-rspack-lib
          ports:
            - name: http
              containerPort: 80
